### ISSUE TITLE
ROS2/C++ Tasks: Stage 1

### ISSUE THREAD

**Issue by Ishaan-Datta** [UBCAgroBot/ROS#35]
## Stage 1: Adapting System Setup:

1. Create singular workspace
2. Create CPP package
3. Rename old Python package
4. Create launch files for the CPP nodes

## Resources
 - [ ] [Example 1](https://github.com/ros2/launch_ros/blob/rolling/ros2launch/examples/example.launch.py)
- [ ] [Example 2](https://github.com/ros2/launch_ros/blob/rolling/ros2launch/examples/includes_example.launch.py)
- [ ] [Parameters](https://docs.ros.org/en/humble/Tutorials/Beginner-CLI-Tools/Understanding-ROS2-Parameters/Understanding-ROS2-Parameters.html)

**Comment by aqil18** [comment]
Creating multiple packages in WS.
Keep top level clean.
![Image](https://github.com/user-attachments/assets/a310796e-e99f-47d2-b553-b569d383632d)

**Comment by aqil18** [comment]
Nodes are not installing packages correctly
![Image](https://github.com/user-attachments/assets/57cf8810-9846-4b2d-af93-9e9144e0f9ea)

**Comment by aqil18** [comment]
Readded the docker image
![Image](https://github.com/user-attachments/assets/7d0fbe8e-dec4-48e6-9094-46c975df07fc)

**Comment by aqil18** [comment]
More missing packages -> looks like the cv2, serial and serial bridge have been installed
![Image](https://github.com/user-attachments/assets/462b8e8b-5785-4895-893c-cdb6a60bdf83)

**Comment by Ishaan-Datta** [comment]
follow the remote dev container steps (https://ubcagrobotappliedai.atlassian.net/wiki/spaces/SysArch/pages/42827792/Jetson+Remote+Access#%5CuD83D%5CuDCD8-Remote-VSCode-Dev-Containers%3A) and run this again in the right container (agrobotappliedai/jetsoncontainers-dev:latest)

**Comment by aqil18** [comment]
- package xml needs updating too

**Comment by aqil18** [comment]
- Need to test the launch file for cpp on jetson ros container
   - Fix any issues with dummy cpp class
- Need to regression test on python launch
